### ISSUE TITLE
how to excute on Mac?

### ISSUE THREAD

**Issue by internalG** [jojje/imdb-sqlite#1]
$pip3 install imdb-sqlite
$ imdb-sqlite
-bash: imdb-sqlite: command not found
$ python3 imdb-sqlite
/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'imdb-sqlite': [Errno 2] No such file or directory

**Comment by internalG** [comment]
well. it seems it's not ready on mac. Failed both 2.7 and 3.6 on mac.

**Comment by jojje** [comment]
Apologies for the late reply. Github notification doesn't seem to have fired for this issue (!?).
My guess is that something is incorrectly configured with your python interpreter.

I successfully installed an ran this script on windows, linux (alpine) and MacOS. The latter with both Homebrew's python3 as well as the python3 can be [downloaded](https://www.python.org/downloads/release/python-365/) from python.org.

E.g.
```
$ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3

$ which imdb-sqlite
/Library/Frameworks/Python.framework/Versions/3.6/bin/imdb-sqlite

$ imdb-sqlite -h
usage: imdb-sqlite [-h] [--db FILE] [--cache-dir DIR] [--verbose]

Imports imdb tsv interface files into a new sqlitedatabase. Fetches them from
imdb if not present onthe machine.

optional arguments:
  -h, --help       show this help message and exit
  --db FILE        Connection URI for the database to import into. (default:
                   imdb.db)
  --cache-dir DIR  Download cache dir where the tsv files from imdb will be
                   stored before the import. (default: downloads)
  --verbose        Show database interaction (default: False)
```
