### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by LucasRibeiroRJBR** [jojje/imdb-sqlite#2]
Your work is excellent, but I missed UML diagram for easy DB understanding. Would this one be correct, based on what I analyzed on your DB?
![IMDB](https://user-images.githubusercontent.com/53449579/162642600-31d29dec-7485-4b06-8fdb-152071a1910c.png)

**Comment by jojje** [comment]
Looks accurate. It all centers on the title.
A title can be a movie or a tv show, and a such not all titles have episodes. If they don't, then they're movies.

All titles have ratings and people who worked on them in some capacity to make them happen (crew; directors, actors ...). Some have different names/aliases in different countries (a.k.as), but not all.

**Comment by jojje** [comment]
Clarified in the Readme for the latest release. Closing.
